check for no soundcards or other alsa error

diff --git a/alsa-capabilities b/alsa-capabilities
--- a/alsa-capabilities
+++ b/alsa-capabilities
@@ -96,6 +96,7 @@ function fetch_alsa_outputinterfaces() {
     [[ ! -z "${DEBUG}" ]] && debug "entering \`${FUNCNAME}' with arguments \`$*'"
     res=""
     aplay_output=""
+    aplay_msg_nosoundcards_re="no[[:space:]]soundcards"
     
     ## to see how the script behaves with a certain output of aplay -l
     ## on a particular host, store it's output in a file and supply
@@ -104,10 +105,15 @@ function fetch_alsa_outputinterfaces() {
     ## test will fail, hopefully with some grace.
     if [[ -z "${TESTFILE}" ]]; then
 	## store the output of `aplay -l`
-	aplay_output="$(${CMD_APLAY} -l)"
-	if [[ $? -ne 0 ]] || [[ -z "${aplay_output}" ]]; then
+	res="$(${CMD_APLAY} -l 2>&1)"
+	if [[ $? -ne 0 ]]; then
+	    die "cannot continue, because alsa reported the following error:\n\`${res}'\n"
+	fi
+	if [[ "${res}" ~= aplay_msg_nosoundcards_re ]]; then
 	    die "cannot continue, because alsa found no soundcards in your system."
 	fi
+	## run it again without std_err
+	aplay_output="$(${CMD_APLAY} -l)"
     else
 	if [[ -f "${TESTFILE}" ]]; then
 	    ## get the output from a file for testing purposes
