first working version

diff --git a/mpd-monitor b/mpd-monitor
--- a/mpd-monitor
+++ b/mpd-monitor
@@ -24,7 +24,7 @@
 
 LANG=C
 
-DEBUG=True
+#DEBUG=True
 REMOTEURL="https://raw.githubusercontent.com/ronalde/mpd-configure/mpd-monitor"
 CMD_ALSACAPS="alsa-capabilities"
 ALSACAPS_OUTPUT=""
@@ -89,10 +89,11 @@ check_commands() {
 
 get_mpdconf() {
     
-    ## check each available mpd configuration file in order.
-    ## Return full path to the file or empty string on error.
+    ## check availability if each possible mpd configuration file in
+    ## order.  Return full path to the file or empty string on error.
 
-    [[ ! -z "${DEBUG}" ]] && debug "entering \`${FUNCNAME}' with arguments \`$*'" 
+    [[ ! -z "${DEBUG}" ]] && \
+	debug "entering \`${FUNCNAME}' with arguments \`$*'" 
     
     
     for file in $XDG_CONFIG_HOME/mpd/mpd.conf \
@@ -112,9 +113,10 @@ get_mpdconf() {
 function get_mpdconf_parameter() {
 
     ## look up a parameter in the mpd configuration file and return
-    ## its value or an empy string.
+    ## its value, return an error when not found.
     
-    [[ ! -z "${DEBUG}" ]] && debug "entering \`${FUNCNAME}' with arguments \`$*'" 
+    [[ ! -z "${DEBUG}" ]] && \
+	debug "entering \`${FUNCNAME}' with arguments \`$*'" 
 
     parameter="$1"
 
@@ -172,51 +174,80 @@ get_mpd_device() {
     mpdconf_parameter="device"
     mpd_device="$(get_mpdconf_parameter "${mpdconf_parameter}")"
     
-    if [[ $? -eq 0 ]]; then
-	[[ ! -z "${DEBUG}" ]] && debug "will use mpd device \`${mpd_device}'"
+    if [[ $? -ne 0 ]]; then
+	die "Could not get alsa device from the mpd configuration file."
+    else
+	[[ ! -z "${DEBUG}" ]] && \
+	    debug "will use mpd device \`${mpd_device}'"
 	printf "%s" "${mpd_device}"
     fi
 }
 
 
-get_file_props() {
+get_file_samplerate() {
 
-    ## get the properties of the file currently played by mpd using soxi
+    ## get the sample rate of the file currently played by mpd using soxi
 
-    [[ ! -z "${DEBUG}" ]] && debug "entering \`${FUNCNAME}' with arguments \`$*'"  
-    
-    sr_regexp="Sample Rate[[:space:]]*:[[:space:]]([0-9]*)" # Sample Rate    : 44100
-    se_regexp="Sample Encoding[[:space:]]*:[[:space:]]([0-9]*)-bit.*" # Sample Encoding: 16-bit FLAC
-    #or use Precision      : 16-bit
+    [[ ! -z "${DEBUG}" ]] && \
+	debug "entering \`${FUNCNAME}'"  
+
+    soxi_output="$1"
+
+    # `Sample Rate    : 44100'
+    sr_regexp="Sample Rate[[:space:]]*:[[:space:]]([0-9]*)" 
     
     while read -r line; do 
-
 	if [[ "${line}" =~ ${sr_regexp} ]]; then
 	    file_samplerate="${BASH_REMATCH[1]}"
 	    [[ ! -z "${DEBUG}" ]] && \
 		debug "file_samplerate: \`${file_samplerate}'."
-	    
-	elif [[ "${line}" =~ ${se_regexp} ]]; then 
-	    file_sampleencoding="${BASH_REMATCH[1]}"
-	    [[ ! -z "${DEBUG}" ]] && \
-		debug "file_sampleencoding: \`${file_sampleencoding}'."
-
+	    printf "%s" "${file_samplerate}"
 	fi
-    done<<<"$(${CMD_SOXI} "${currentfile_fullpath}")"
-
+    done<<<"${soxi_output}"
     
 }
 
-get_alsa_props() {
+get_file_sampleencoding() {
+
+    ## get the sample encoding of the file currently played by mpd using soxi
+
+    [[ ! -z "${DEBUG}" ]] && \
+	debug "entering \`${FUNCNAME}'"  
+
+    soxi_output="$1"
+
+    # `Sample Encoding: 16-bit FLAC'
+    # or use `Precision      : 16-bit'
+    se_regexp="Sample Encoding[[:space:]]*:[[:space:]]([0-9]*)-bit.*" 
+    
+    while read -r line; do 
+
+	if [[ "${line}" =~ ${se_regexp} ]]; then 
+	    file_sampleencoding="${BASH_REMATCH[1]}"
+	    [[ ! -z "${DEBUG}" ]] && \
+		debug "file_sampleencoding: \`${file_sampleencoding}'."
+	    printf "%s" "${file_sampleencoding}"
+	    
+	fi
+    done<<<"${soxi_output}"
+    
+}
+
+get_alsa_samplerate() {
 
     ## get the properties of the file currently played by mpd using alsa
 
-    [[ ! -z "${DEBUG}" ]] && debug "entering \`${FUNCNAME}' with arguments \`$*'"
-     
+    [[ ! -z "${DEBUG}" ]] && \
+	debug "entering \`${FUNCNAME}' with arguments \`$*'"
+
+    alsa_streamfile="$1"
+
+    ## USB streamfile
     # Sample rate: Momentary freq = 95999 Hz (0xb.fff8)
     sr_regexp="Momentary freq[[:space:]]=[[:space:]]([0-9]*)[[:space:]]Hz[[:space:]].*"
-    # Encoding format: Format: S32_LE
-    se_regexp="Format:[[:space:]]([A-Z_0-9]*)" 
+    ## Any hwparamsfile
+    ## rate: 96000 (96000/1)
+    sr_regexp="^rate:[[:space:]]([0-9]*)[[:space:]]\(.*\)"
     
     while read -r line; do 
 	
@@ -224,52 +255,110 @@ get_alsa_props() {
 	    alsa_samplerate="${BASH_REMATCH[1]}"
 	    [[ ! -z "${DEBUG}" ]] && \
 		debug "alsa_samplerate: \`${alsa_samplerate}'."
-	    
-	elif [[ "${line}" =~ ${se_regexp} ]]; then 
-	    alsa_sampleencoding="${BASH_REMATCH[1]}"
-	    [[ ! -z "${DEBUG}" ]] && \
-		debug "alsa_sampleencoding: \`${alsa_sampleencoding}'."
-
+	    printf "%s" "${alsa_samplerate}"
 	fi
     done<"${alsa_streamfile}"
     
     
 }
 
+get_alsa_sampleencoding() {
+
+    ## get the properties of the file currently played by mpd using alsa
+
+    [[ ! -z "${DEBUG}" ]] && \
+	debug "entering \`${FUNCNAME}' with arguments \`$*'"
+
+    alsa_streamfile="$1"
+
+    ## USB streamfile
+    ## Encoding format: Format: S32_LE
+    se_regexp="Format:[[:space:]]([A-Z_0-9]*)" 
+
+    ## Any hwparams file
+    ## format: S32_LE
+    se_regexp="^format:[[:space:]](.*)"
+    
+    while read -r line; do 
+	
+	if [[ "${line}" =~ ${se_regexp} ]]; then 
+	    alsa_sampleencoding="${BASH_REMATCH[1]}"
+	    [[ ! -z "${DEBUG}" ]] && \
+		debug "alsa_sampleencoding: \`${alsa_sampleencoding}'."
+	    printf "%s" "${alsa_sampleencoding}"
+	fi
+    done<"${alsa_streamfile}"  
+    
+}
+
+
 function get_alsa_streamfile() {
     ## use alsa-capabilities to get the stream file for the (hardware
     ## address of the) alsa interface specified in the mpd
     ## configuration file (needed for `get_alsa_props').
 
-    [[ ! -z "${DEBUG}" ]] && debug "entering \`${FUNCNAME}' with arguments \`$*'"
+    [[ ! -z "${DEBUG}" ]] && \
+	debug "entering \`${FUNCNAME}' with arguments \`$*'"
 
     #monitor file           =  /proc/asound/card1/stream0
+    alsa_streamfile=""
     alsa_streamfile_regexp="monitor[[:space:]]file[[:space:]]*=[[:space:]]*(.*)"
     alsa_hwaddress="$(get_mpd_device)"
-    
-    if [[ -x "${CMD_ALSACAPS}" ]]; then 
-	ALSACAPS_OUTPUT="$(bash ${CMD_ALSACAPS} -a "${alsa_hwaddress}")"
-    else
-	[[ ! -z "${DEBUG}" ]] && \
-	    debug "no local copy of \`alsa-capabilities', will fetch it from github."
-	
-	ALSACAPS_OUTPUT="$(bash <(wget -q -O - "${REMOTEURL}/${CMD_ALSACAPS}") -a "${alsa_hwaddress}")"
-	
-    fi
-    
-    while read -r line; do 
-	if [[ "${line}" =~ ${alsa_streamfile_regexp} ]]; then
-	    alsa_streamfile="${BASH_REMATCH[1]}"
-	fi
-    done<<<"${ALSACAPS_OUTPUT}"
+    alsa_hwaddress="${alsa_hwaddress/hw:/}"
+    alsa_dev_nr="${alsa_hwaddress%%,*}"
+    [[ ! -z "${DEBUG}" ]] && \
+	debug "using alsa_dev_nr: \`${alsa_dev_nr}'"
 
-    if [[ ! -f "${alsa_streamfile}" ]]; then
-	die "alsa streamfile \`${alsa_streamfile}' is not found or not accessible."
+    alsa_if_nr="${alsa_hwaddress##*,}"
+    [[ ! -z "${DEBUG}" ]] && \
+	debug "using alsa_if_nr: \`${alsa_if_nr}'"
+
+    alsa_if_hwparamsfile="/proc/asound/card${alsa_dev_nr}/pcm${alsa_if_nr}p/sub0/hw_params"
+    [[ ! -z "${DEBUG}" ]] && \
+	debug "alsa_if_hwparamsfile: \`${alsa_if_hwparamsfile}'" 
+    
+    
+    if [[ ! -f "${alsa_if_hwparamsfile}" ]]; then
+	die "alsa_if_hwparamsfile \`${alsa_if_hwparamsfile}' is not accessible."
     else
-	printf "%s" "${alsa_streamfile}"
+	## show on screen
+	    [[ ! -z "${DEBUG}" ]] && \
+	debug "alsa_if_hwparamsfile: \`${alsa_if_hwparamsfile}'" 1>&2;
+	## return it to the calling function
+	printf "%s" "${alsa_if_hwparamsfile}"
     fi
+    
+
     
 }
+
+function weg() {
+
+    ## use local or remote alsa-capabilities script to get the stream file
+    if [[ ! -x "${CMD_ALSACAPS}" ]]; then
+	[[ ! -z "${DEBUG}" ]] && \
+	    debug "\`alsa-capabilities' not available, download it."
+	tmpdir="$(mktemp -d "mpd-configure.XXXX")"
+	res="$(wget -q -O "${tmpdir}/${CMD_ALSACAPS}" "${REMOTEURL}/${CMD_ALSACAPS}")"
+	if [[ $? -ne 0 ]]; then
+	    die "Could not download "${REMOTEURL}/${CMD_ALSACAPS}""
+	else
+	    [[ ! -z "${DEBUG}" ]] && \
+		debug "alsa-capabilities downloaded to \`${tmpdir}/${CMD_ALSACAPS}'"
+	    CMD_ALSACAPS="${tmpdir}/${CMD_ALSACAPS}"
+	fi
+    fi
+
+    source "${CMD_ALSACAPS}"
+    #-a "${alsa_hwaddress}")"
+    
+    jaap="$(OPT_HWFILTER="${alsa_hwaddress}" return_alsa_interface)"
+    printf "contents of jaap:\n" 1>&2;
+    printf "%s\n" "${jaap}" 1>&2;
+    alsa_if_hwparamsfile=""
+
+    }
+
 
 check_commands || exit 1
 
@@ -291,8 +380,19 @@ else
 	debug "checking file: \`${currentfile_fullpath}'."
 fi
 
-get_file_props
+msg_source="encoded"
+msg_actual="decoding"
 
-get_alsa_props
+soxi_output="$(${CMD_SOXI} "${currentfile_fullpath}")"
 
-#get_alsa_streamfile
+file_samplerate="$(get_file_samplerate "${soxi_output}")"
+file_sampleencoding="$(get_file_sampleencoding "${soxi_output}")"
+
+alsa_samplerate="$(get_alsa_samplerate "${alsa_streamfile}")"
+alsa_sampleencoding="$(get_alsa_sampleencoding "${alsa_streamfile}")"
+
+printf "sample rate:\n\t${msg_source}: %s\n\t${msg_actual}:%s\n" \
+       "${file_samplerate}" "${alsa_samplerate}"
+
+printf "sample format:\n\t${msg_source}: %s\n\t${msg_actual}:%s\n" \
+       "${file_sampleencoding}" "${alsa_sampleencoding}"
