in between

diff --git a/pulseaudio-helper b/pulseaudio-helper
--- a/pulseaudio-helper
+++ b/pulseaudio-helper
@@ -8,7 +8,7 @@ OPT_STOP_PULSEAUDIO="${OPT_STOP_PULSEAUDIO:-}"
 OPT_DISABLE_PULSEAUDIO="${OPT_DISABLE_PULSEAUDIO:-}"
 
 ## strings for pulseaudio handling
-CMD_PULSEAUDIO=""
+CMD_PULSEAUDIO="${CMD_PULSEAUDIO:-}"
 PA_CLIENT_USER_CONF_FALLBACKPATH=${HOME}/.pulse/client.conf
 PA_CLIENT_USER_CONF_PATH=${HOME}/.config/pulse/client.conf
 PA_CLIENT_SYSTEM_CONF_PATH=/etc/pulse/client.conf
@@ -46,13 +46,14 @@ function pulseaudio_evaluate_stopping() {
     ## stop pulseaudio if needed. Errors are non fatal.
     ## TODO: check neccessity and/or cleanup
     [[ ! -z "${DEBUG}" ]] && \
-	debug_pahelper "entering \`${FUNCNAME}' with arguments \`$*'"
+	debug_pahelper "${FUNCNAME}: entering \`${FUNCNAME}' with arguments \`$*'"
 
     ## check if its installed
     CMD_PULSEAUDIO="$(which pulseaudio 2>/dev/null)"
     if [[ $? -ne 0  ]]; then
 	[[ ! -z "${DEBUG}" ]] && \
-	    debug_pahelper "disabling of pulseaudio requested but it is not installed."
+	    debug_pahelper "${FUNCNAME}: disabling of pulseaudio requested but \
+it is not installed."
 	CMD_PULSEAUDIO=""
 	return 1
     fi
@@ -61,28 +62,23 @@ function pulseaudio_evaluate_stopping() {
     if [[ $? -ne 0 ]]; then
 	## not running
 	[[ ! -z "${DEBUG}" ]] && \
-	    debug_pahelper "disabling of pulseaudio requested but it is not running."    
+	    debug_pahelper "${FUNCNAME}: disabling of pulseaudio requested but \
+it is not running."    
 	PA_CLIENT_PID=""
 	return 1
     else 
-	## check if it should be permanently disabled
-	if [[ -z "${OPT_DISABLE_PULSEAUDIO}" ]]; then
-	    # disabling should be temporary
-	    printf " * non-permanent disabling of pulseaudio requested.\n" 1>&2;
-	    ## check if there's an existing client.conf and back it up
-	    if [[ -f "${PA_CLIENT_USER_CONF_PATH}" ]]; then
-		PA_CLIENT_CONF="${PA_CLIENT_USER_CONF_PATH}"
-		PA_CLIENT_CONF_BACKUP="$(pulseaudio_backup_clientconf "${PA_CLIENT_CONF}")"
-		if [[ $? -ne 0 ]]; then
-		    return 1
-		fi
+	# temporary disable pulseaudio client
+	printf " * will temporary disable pulseaudio client.\n" 1>&2;
+	## check if there's an existing client.conf and back it up
+	if [[ -f "${PA_CLIENT_USER_CONF_PATH}" ]]; then
+	    PA_CLIENT_CONF="${PA_CLIENT_USER_CONF_PATH}"
+	    PA_CLIENT_CONF_BACKUP="$(pulseaudio_backup_clientconf "${PA_CLIENT_CONF}")"
+	    if [[ $? -ne 0 ]]; then
+		return 1
 	    fi
-	    ## stop it
-	else
-	    ## disabling should be permanent
-	    printf " * permanent disabling of pulseaudio requested.\n" 1>&2;
 	fi
-
+	## stop it
+	
 	res="$(pulseaudio_stop "${PA_CLIENT_PID}")"
 	if [[ $? -ne 0 ]]; then
 	    PA_CLIENT_PID=""
@@ -95,104 +91,44 @@ function pulseaudio_evaluate_stopping() {
 }
 
 
-function pulseaudio_evaluate_restoring() {
-    ## evaluate if pulseaudio configuration and/or running state needs
-    ## to be restored.
-    ## TODO: check neccessity and/or cleanup
-
-    if [[ -z "${CMD_PULSEAUDIO}" ]]; then
-	[[ ! -z "${DEBUG}" ]] && \
-	    debug_pahelper "no pulseaudio command found in path."
-	return 0
-    else 
-	## check if config restoring is required
-	if [[ -z ${PA_CLIENT_CONF} ]]; then
-	    if [[ ! -z ${OPT_DISABLE_PULSEAUDIO} ]]; then
-		[[ ! -z ${DEBUG} ]] && \
-		    debug_pahelper "${MSG_PA_CONFFILE} existed, but no need to restore it."
-	    else
-		[[ ! -z ${DEBUG} ]] && \
-		    debug_pahelper "${MSG_PA_CONFFILE} existed and need to be restored from \`${PA_CLIENT_CONF}.backup-$$'."
-		res="$(pulseaudio_restore_clientconf)"
-		if [[ $? -ne 0 ]]; then
-		    [[ ! -z ${DEBUG} ]] && \
-			debug_pahelper "pulseaudio_restore_clientconf \
-returned: \`${res}'."
-		    printf "  * %s\n" "${res}" 1>&2;
-		fi
-	    fi
-	fi
-    fi
-
-    if [[ -z ${PA_CLIENT_PID} ]]; then
-	[[ ! -z ${DEBUG} ]] && \
-	    debug_pahelper "pulseaudio was not running."
-	return 0
-    else
-	[[ ! -z ${DEBUG} ]] && \
-	    debug_pahelper "pulseaudio was running with pid ${PA_CLIENT_PID}".
-	## pulseaudio was running
-	if [[ ! -z "${OPT_DISABLE_PULSEAUDIO}" ]]; then
-	    [[ ! -z ${DEBUG} ]] && \
-		debug_pahelper "no need to restart it."
-	else
-	    [[ ! -z ${DEBUG} ]] && \
-		debug_pahelper "need to restart it."
-		pulseaudio_start	    
-	fi
-    fi
-    
-}
-
-
 function pulseaudio_restore_clientconf() {
     ## restore backed up client configuration if created by script.
     ## TODO: check neccessity and/or cleanup
     [[ ! -z "${DEBUG}" ]] && \
-	debug_pahelper "entering \`${FUNCNAME}' with arguments \`$*'"
+	debug_pahelper "${FUNCNAME}: entering \`${FUNCNAME}' with arguments \`$*'"
 
-    if [[ ! -z ${PA_CLIENT_CONF_BACKUP} ]]; then 
-	if [[ ! -f "${PA_CLIENT_CONF_BACKUP}" ]]; then
-	    [[ ! -z "${DEBUG}" ]] && \
-		debug_pahelper "backup of ${MSG_PA_CONFFILE} \
- \`${PA_CLIENT_CONF_BACKUP}' not found."
+    if [[ -f "${PA_CLIENT_CONF_BACKUP}" ]]; then
+	res="$(cp -av "${PA_CLIENT_CONF_BACKUP}" "${PA_CLIENT_CONF}")"
+	if [[ $? -ne 0 ]]; then
+	    ## error restoring
+	    ## TODO: make fatal?
+	    printf "Could not restore original %s \`%s'.\n" \
+		   "${MSG_PA_CONFFILE}" "${PA_CLIENT_CONF}"
+	    printf "Backup created in \`%s'." \
+		   "${PA_CLIENT_CONF_BACKUP}"
 	    return 1
 	else
-	    res="$(cp -av "${PA_CLIENT_CONF_BACKUP}" "${PA_CLIENT_CONF}")"
+	    ## succesfully copied backup conf to client.conf
+	    [[ ! -z "${DEBUG}" ]] && \
+		debug_pahelper \
+		    "${MSG_PA_CONFFILE} \`${PA_CLIENT_CONF_BACKUP}' \
+successfully restored to \`${PA_CLIENT_CONF}'."
+	    ## remove the backup
+	    res="$(rm "${PA_CLIENT_CONF_BACKUP}")"
 	    if [[ $? -ne 0 ]]; then
-		## error restoring
 		[[ ! -z "${DEBUG}" ]] && \
-		    debug_pahelper "error restoring ${MSG_PA_CONFFILE} \
- \`${PA_CLIENT_CONF_BACKUP}' to \`${PA_CLIENT_CONF}': \
- \`${res}'"
-		## TODO: make fatal?
-		printf "Could not restore original %s \`%s'.\n" \
-		       "${MSG_PA_CONFFILE}" "${PA_CLIENT_CONF}"
-		printf "Backup created in \`%s'." \
-		       "${PA_CLIENT_CONF_BACKUP}"
+		    debug_pahelper "${FUNCNAME}: removal of ${MSG_PA_CONFFILE} \
+ \`${PA_CLIENT_CONF_BACKUP}' failed with error: \`${res}'."
 		return 1
 	    else
-		## succesfully copied backup conf to client.conf
 		[[ ! -z "${DEBUG}" ]] && \
-		    debug_pahelper \
-			"${MSG_PA_CONFFILE} \`${PA_CLIENT_CONF_BACKUP}' \
-successfully restored to \`${PA_CLIENT_CONF}'."
-		## remove the backup
-		res="$(rm "${PA_CLIENT_CONF_BACKUP}")"
-		if [[ $? -ne 0 ]]; then
-		    [[ ! -z "${DEBUG}" ]] && \
-			debug_pahelper "removal of ${MSG_PA_CONFFILE} \
- \`${PA_CLIENT_CONF_BACKUP}' failed with error: \`${res}'."
-		    return 1
-		else
-		    [[ ! -z "${DEBUG}" ]] && \
-			debug_pahelper "backup ${MSG_PA_CONFFILE} \
+		    debug_pahelper "${FUNCNAME}: backup ${MSG_PA_CONFFILE} \
  \`${PA_CLIENT_CONF_BACKUP}' successfully removed."
-		    return 0
-		fi
+		return 0
 	    fi
 	fi
     fi
+
 }
 
 
@@ -200,17 +136,17 @@ function pulseaudio_is_running() {
     ## returns pid of pulseaudio if running, otherwise empty
     ## TODO: check neccessity and/or cleanup
     [[ ! -z "${DEBUG}" ]] && \
-	debug_pahelper "entering \`${FUNCNAME}' with arguments \`$*'"
-    
-    PA_CLIENT_PID="$(pgrep -u ${USER} pulseaudio)"
+	debug_pahelper "${FUNCNAME}: entering \`${FUNCNAME}' with arguments \`$*'"
+    PA_CLIENT_PID="$1"
+    res="$(ps -fp "${PA_CLIENT_PID}")"
     if [[ $? -ne 0 ]]; then
 	[[ ! -z "${DEBUG}" ]] && \
-	    debug_pahelper "pulseaudio is not running"
+	    debug_pahelper "${FUNCNAME}: pulseaudio is not running"
 	return 1
     else
 	## return its pid
 	[[ ! -z "${DEBUG}" ]] && \
-	    debug_pahelper "pulseaudio is running: \`${PA_CLIENT_PID}'"
+	    debug_pahelper "${FUNCNAME}: pulseaudio is running: \`${PA_CLIENT_PID}'"
 	printf "%s" "${PA_CLIENT_PID}"
     fi
 }
@@ -219,19 +155,19 @@ function pulseaudio_start() {
     ## start pulseaudio
     ## TODO: check neccessity and/or cleanup
     [[ ! -z "${DEBUG}" ]] && \
-	debug_pahelper "entering \`${FUNCNAME}' with arguments \`$*'"
+	debug_pahelper "${FUNCNAME}: entering \`${FUNCNAME}' with arguments \`$*'"
     
     if [[ ! -z "$(pulseaudio_is_running)" ]]; then
 	## pulseaudio is running
 	[[ ! -z "${DEBUG}" ]] && \
-	    debug_pahelper "not starting pulseaudio, is already running."
+	    debug_pahelper "${FUNCNAME}: not starting pulseaudio, is already running."
     else
 	## pulseaudio is not running, start it
 	res=$(${CMD_PULSEAUDIO} --start)
 	if [[ ! -z "$(pulseaudio_is_running)" ]]; then	
-	    [[ ! -z "${DEBUG}" ]] && debug_pahelper "pulseaudio started."
+	    [[ ! -z "${DEBUG}" ]] && debug_pahelper "${FUNCNAME}: pulseaudio started."
 	else
-	    [[ ! -z "${DEBUG}" ]] && debug_pahelper "pulseaudio could not be started."
+	    [[ ! -z "${DEBUG}" ]] && debug_pahelper "${FUNCNAME}: pulseaudio could not be started."
 	fi
     fi
 
@@ -241,7 +177,7 @@ function pulseaudio_check_autospawn() {
     ## check if autospawning of the pulseaudio daemon is disabled in
     ## its configuration files.
     [[ ! -z "${DEBUG}" ]] && \
-	debug_pahelper "entering \`${FUNCNAME}' with arguments \`$*'"
+	debug_pahelper "${FUNCNAME}: entering \`${FUNCNAME}' with arguments \`$*'"
 
     noautospawn=""
     noautospawn_regexp="^[[:space:]]*autospawn[[:space:]]*=[[:space:]]*([Nn]o|[Oo]ff|[Ff]alse|0)"
@@ -263,7 +199,7 @@ function pulseaudio_check_autospawn() {
 	    if [[ "${line}" =~ ${noautospawn_regexp} ]]; then
 		noautospawn=True
 		[[ ! -z ${DEBUG} ]] && \
-		    debug_pahelper "autospawning was already disabled \
+		    debug_pahelper "${FUNCNAME}: autospawning was already disabled \
 in \`${conffile}' by line \`${line}'."
 		break
 	    fi
@@ -282,7 +218,7 @@ function pulseaudio_disable_respawn() {
     ## disables spawning of pulseaudio
     ## TODO: check neccessity and/or cleanup
     [[ ! -z "${DEBUG}" ]] && \
-	debug_pahelper "entering \`${FUNCNAME}' with arguments \`$*'"
+	debug_pahelper "${FUNCNAME}: entering \`${FUNCNAME}' with arguments \`$*'"
 
     pulseaudio_check_autospawn
     if [[ $? -ne 0 ]]; then
@@ -290,12 +226,12 @@ function pulseaudio_disable_respawn() {
 	res="$(printf "autospawn=no\n" > "${PA_CLIENT_USER_CONF_PATH}")"
 	if [[ $? -ne 0 ]]; then
 	    [[ ! -z "${DEBUG}" ]] && \
-		debug_pahelper "creating ${MSG_PA_CONFFILE} \`${PA_CLIENT_USER_CONF_PATH}' \
+		debug_pahelper "${FUNCNAME}: creating ${MSG_PA_CONFFILE} \`${PA_CLIENT_USER_CONF_PATH}' \
 failed with error: \`${res}'."
 	    return 1
 	else
 	    [[ ! -z "${DEBUG}" ]] && \
-		debug_pahelper "respawning disabled by creating \
+		debug_pahelper "${FUNCNAME}: respawning disabled by creating \
 ${MSG_PA_CONFFILE} \`${PA_CLIENT_USER_CONF_PATH}'."
 	    return 0
 	fi
@@ -311,20 +247,20 @@ function pulseaudio_backup_clientconf() {
     ## success, 1 on error.
     ## TODO: check neccessity and/or cleanup
     [[ ! -z "${DEBUG}" ]] && \
-	debug_pahelper "entering \`${FUNCNAME}' with arguments \`$*'"
+	debug_pahelper "${FUNCNAME}: entering \`${FUNCNAME}' with arguments \`$*'"
 
     PA_CLIENT_CONF="$1"
     PA_CLIENT_CONF_BACKUP="${PA_CLIENT_CONF}.backup-$$"
     res="$(cp -av "${PA_CLIENT_CONF}" "${PA_CLIENT_CONF_BACKUP}" 2>&1)"
     if [[ $? -ne 0 ]]; then
 	[[ ! -z "${DEBUG}" ]] && \
-	    debug_pahelper "could not create a backup of ${MSG_PA_CONFFILE} \
+	    debug_pahelper "${FUNCNAME}: could not create a backup of ${MSG_PA_CONFFILE} \
 \`${PA_CLIENT_CONF}' to \`${PA_CLIENT_CONF_BACKUP}. \
 failed with error: \`${res}'."
 	return 1
     else 
 	[[ ! -z "${DEBUG}" ]] && \
-	    debug_pahelper "${MSG_PA_CONFFILE} \`${PA_CLIENT_CONF}' \
+	    debug_pahelper "${FUNCNAME}: ${MSG_PA_CONFFILE} \`${PA_CLIENT_CONF}' \
 backed up to \`${PA_CLIENT_CONF_BACKUP}'."
 	printf "${PA_CLIENT_CONF_BACKUP}"
 	return 0
@@ -337,7 +273,7 @@ function pulseaudio_stop() {
     ## temporary or permanently keeping it from respawning.
     ## TODO: check neccessity and/or cleanup
     [[ ! -z "${DEBUG}" ]] && \
-	debug_pahelper "entering \`${FUNCNAME}' with arguments \`$*'"
+	debug_pahelper "${FUNCNAME}: entering \`${FUNCNAME}' with arguments \`$*'"
 
     ## check if its running
     PA_CLIENT_PID="$1"
@@ -346,7 +282,7 @@ function pulseaudio_stop() {
     pulseaudio_disable_respawn
     if [[ $? -ne 0 ]]; then
 	msg="unable to keep pulseaudio from respawning"
-	[[ ! -z ${DEBUG} ]] && debug_pahelper "${msg}"
+	[[ ! -z ${DEBUG} ]] && debug_pahelper "${FUNCNAME}: ${msg}"
 	printf "%s" "${msg}"
 	return 1
     else
@@ -354,35 +290,36 @@ function pulseaudio_stop() {
 	res=$(${CMD_PULSEAUDIO} -vv --kill)
 	if [[ $? -ne 0 ]]; then
 	    msg="pulseaudio --kill failed to stop PID ${PA_CLIENT_PID} with return code \`${res}'."
-	    [[ ! -z ${DEBUG} ]] && debug_pahelper "${msg}"
+	    [[ ! -z ${DEBUG} ]] && debug_pahelper "${FUNCNAME}: ${msg}"
 	    ## try killing it by its pid
 	    res="$(kill -9 ${PA_CLIENT_PID})"
 	    if [[ $? -ne 0 ]]; then
 		msg="unable to kill pulseaudio by sending SIGTERM to its PID."
-		[[ ! -z ${DEBUG} ]] && debug_pahelper "${msg}"
+		[[ ! -z ${DEBUG} ]] && debug_pahelper "${FUNCNAME}: ${msg}"
 		printf "%s" "${msg}"
 		return 1
 	    else
 		[[ ! -z ${DEBUG} ]] && \
-		    debug_pahelper "succesfully killed pulseaudio with PID ${PA_CLIENT_PID}."
+		    debug_pahelper "${FUNCNAME}: succesfully killed \
+pulseaudio client with PID ${PA_CLIENT_PID}."
 		return 0
 	    fi
 	else
 	    [[ ! -z ${DEBUG} ]] && \
-		debug_pahelper "pulseaudio --kill reported it succesfully killed PID ${PA_CLIENT_PID}."
-	    ## check if that worked
-	    if [[ -z "$(pulseaudio_is_running)" ]]; then
-		[[ ! -z "${DEBUG}" ]] && \
-		    debug_pahelper "pulseaudio is definitely killed."
-		return 0
-	    else
-		msg="pulseaudio respawned. ${MSG_ERROR_UNEXPECTED}."
-		[[ ! -z "${DEBUG}" ]] && \
-		    debug_pahelper "pulseaudio respawned. ${MSG_ERROR_UNEXPECTED}."
-		printf "%s" "${msg}"
-		return 1
+		debug_pahelper "${FUNCNAME}: pulseaudio --kill reported it succesfully killed PID ${PA_CLIENT_PID}."
+	    ## wait for pulseaudio to exit check if that worked
+	    # if [[ -z "$(pulseaudio_is_running)" ]]; then
+	    # 	[[ ! -z "${DEBUG}" ]] && \
+	    # 	    debug_pahelper "${FUNCNAME}: pulseaudio is definitely killed."
+	    # 	return 0
+	    # else
+	    # 	msg="pulseaudio respawned. ${MSG_ERROR_UNEXPECTED}."
+	    # 	[[ ! -z "${DEBUG}" ]] && \
+	    # 	    debug_pahelper "${FUNCNAME}: pulseaudio respawned. ${MSG_ERROR_UNEXPECTED}."
+	    # 	printf "%s" "${msg}"
+	    # 	return 1
 
-	    fi
+	    # fi
 	fi
     fi
     
